import IMAGE from "../ProductImg";
import PRODUCTS from "./Komponente/NavBar/NavProducts/ProductNames";
export const ProductData = [
  {
    name: PRODUCTS.allProducts.pvcProzor1,
    imgCover: IMAGE.pvcProzor1CoverImg,
    imgVideo: "https://www.drutex.eu/media/_upload/produkty/iglo_light/video/iglo_light.mp4",
    options: {
      firstOption:
        "Modern design, a lot of daylight and great parameters regarding energy efficiency, waterproofness, resistance to wind and air permeability!",
      secondOption: [
        "  Elegant design expressed in the slim, narrow and rounded lines makes the original Drutex profile with its central aluminium handle placed on the movable post the most narrow profile from the traditional ones.",
        "A lot of daylight, as a result of the most narrow profiles and bigger glazing surface comparing to standard systems.",
        "Wide range of foil colours allows any interior design.",
        "High safety level ensured by the high-quality five-chamber profiles in A class, made exclusively of prime material.",
        "Window resistance and stability thanks to the big original steel reinforcement chamber and modern fittings with two anti-burglary bolts.",
        "High functionality thanks to the modern fittings and so called handle drive gear that enables its central position on the sash assembly – the movable post.",
        "Great energy efficiency thanks to the optimum profile structure, EPDM seal and the galvanized steel thermal frames or optionally the innovative Swisspacer Ultimate that guarantee energy savings even up to 12%* and low-emission glass packages.",
        "In standard V-Perfect, that allows to connect the profiles perfectly and it guarantees better clamp and wielding control, and, as a result, very good parameters in the resistance tests of the corners.",
      ],
      thirdOption: ["IGLO Energy", "IGLO Energy Classic", "IGLO 5", "IGLO 5 Classic"],
    },
    material: [
      "The original five-chamber frame and sash profile made exclusively of prime material in A-class. Frame and sash installation depth of 70 mm with 32% more narrow movable post with symmetrically placed aluminium handle (the frame and sash composition is 108 mm, the width of movable post – 112 mm). A lot of daylight and modern glazing thanks to the bigger glass surface comparing to traditional profiles.",
      "Glazing thickness up to 40 mm. One-chamber glass package with thermal transmittance coefficient Ug =1,0 W/(m2K) according to PN-EN674 in standard. The possibility to apply packages of Ug = 0,6 W/(m2K)coefficient. The possibility to apply glass with enhanced sound insulation, tempered, safety, anti-burglary, ornament, solar protective.",
      " MACO MULTI MATIC KS with two anti-burglary bolts in standard. Silber-Look coating and line-shaped concavities in espagnolette, optionally hinges hidden in the fitting notch; window equipped with lifiting sash and handle missplacement blockage *, micro-ventilation in a slot **.",
    ],
  },
  {
    name: PRODUCTS.allProducts.pvcProzor2,
    imgCover: IMAGE.pvcProzor2overImg,
    imgVideo: "https://www.drutex.eu/media/_upload/produkty/IGLO_ENERGY/video/iglo_energy.mp4",
    options: {
      firstOption:
        "A perfect solution for demanding Clients! Modern design, innovative technology and high energy efficiency that ensure lower heating bills!",
      secondOption: [
        "Energy efficiency as a result of the optimal profile structure, specially designed sealing system made of foamed EPDM and glass packages with low thermal transmittance.",
        "Modern design that is guaranteed by the slim, round-shaped profile.",
        "High safety level guaranteed by  two anti-burglary bolts in standard.",
        "Wide range veneer colours that enusre numerous interior design styles.",
        "Good parameters of sound insulation that ensure acoustic comfort even in places with intense traffic.",
        "Great parameters of air permeability and water resistance as a result of using triple sealing.",
        "System offers great resistance to wind  load thanks to optimal reinforcement.",
      ],
      thirdOption: ["IGLO Light", "IGLO Energy Classic", "IGLO 5", "IGLO 5 Classic"],
    },
    material: [
      "7-chamber frame and sash profiles made exclusively of prime material in A-class with installation depth 82 mm.",
      "Maximal glazing thickness up to 48 mm. Glass package  4/18/4/18/4 with thermal transmittance  Ug = 0,5 W/(m2K)in standard; – the possibility to apply four-glass package filled with krypton with Ug = 0,3 W/(m2K); the possibility to apply glass with enhanced sound insulation, tempered, safety, anti-burglary, ornament or solar protective.",
      "MACO MULTI MATIC KS with two anti-burglary bolts in standard. Silber-Look coating and line-shaped concavities in espagnolette, optionally hinges hidden in the fitting notch; solutions in anti-burglary class RC 2 and RC 2N, window equipped with lifiting sash and handle missplacement blockage *, micro-ventilation in a slot **.",
    ],
  },
  {
    name: PRODUCTS.allProducts.drvoAluminiumProzor1,
    imgCover: IMAGE.drvoAluminiumProzor1CoverImg,
    imgVideo: "https://www.drutex.eu/media/_upload/produkty/DUOLINE/video/duoline.mp4",
    options: {
      firstOption: "Perfect combination of durability and wood aesthetics.",
      secondOption: [
        "Classic and elegant design coherent with current architectural trends.",
        "Great selection of colours for the interior thanks to the wide colour palette for aluminum and wood.",
        "Lots of design possibilities regarding the shapes – from rectangles, trapezoids, arches, circles and other non-standard shapes.",
        "Great parameters in energy efficiency and sound insulation.",
        "High safety level guaranteed by the stability of aluminum profile  combined with high-quality Maco fittings.",
        "Easy for upkeep and care, thanks to the external aluminum profile. ",
      ],
      thirdOption: ["IGLO Energy", "IGLO Energy Classic", "IGLO 5", "IGLO 5 Classic"],
    },
    material: [
      "Possibility to choose between profiles with three installation depths: 68mm, 78mm, 88 mm in two types of wood: three- or four-layer solid square timber: meranti 450+, pine, with aluminum clad on the outside.",
      "Glass – Two-glass package with 24 mm thickness in standard, with thermal transmittance coefficient Ug = 1,0 W/(m2K) according to the PN-EN674 norm; the possibility to apply two- or three-glass packages For Duoline 68 mm – max. glass package thickness is 46 mm with thermal transmittance coefficient - Ug = 0,6 W/(m2K). For Duoline 78 mm – max. glass package thickness is 50 mm with thermal transmittance coefficient - Ug = 0,5 W/(m2K) For Duoline 88 mm – max. glass package thickness is 50 mm with thermal transmittance coefficient - Ug = 0,5 W/(m2K) The possibility to apply glass with enhanced sound insulation, tempered, safety, anti-burglary, ornament or solar protective..",
      "Maco Multi Matic KS; Two anti-burglary bolts in standard; window is equipped with sash lifting and handle missplacement blockage*; micro-ventilation in a slot **; optionally hidden hinges.",
    ],
  },
  {
    name: PRODUCTS.allProducts.aluminiumProzor1,
    imgCover: IMAGE.aluminiumProzor1CoverImg,
    imgVideo: "https://www.drutex.eu/media/_upload/produkty/mb-45/video-okno/okno_mb_45.mp4",
    options: {
      firstOption: "Modern aluminium system that allows to create diverse interior design.",
      secondOption: [
        "Modern and stable aluminum profile allows to achieve the effect of one surpace frame and the sash on the outside, after the window has been closed.",
        "Possibility to customize the interior as a result of the wide  RAL colour range.",
        "The system is compatible with other aluminum systems in DRUTEX offer.",
        "The system allows to apply one- or two- glass packages.",
        "Tightness is ensured by the use of special seals made of synthetic rubber EPDM that guarantees lond lasting of the material.",
        "A significant advantage of MB-45 system is the possibility to bend profiles, i.a. the frames and sashes, which enables to produce various types of arch structures. ",
        "High comfort of usage and the minimal need for maintenance, and long durability. ",
      ],
      thirdOption: ["MB-70HI", "MB-70", "IGLO 5", "MB-86SI"],
    },
    material: [
      "Aluminium profile  45mm ( frame) and 54mm (sash) depth.",
      "Glass packages available up to 24 mm; the possibility to apply glass with enhanced sound insulation, tempered, safety, anti-burglary, ornament and solar protective.",
      "Maco Multi Matic KS with two anti-burglary bolts. Window equipped with a blockage against handle misplacement and a sash lift *; micro-ventilation in a slot **; *Depending on the window height **for tilt and turn windows",
    ],
  },
  {
    name: PRODUCTS.allProducts.aluminiumProzor2,
    imgCover: IMAGE.aluminiumProzor2CoverImg,
    imgVideo: "https://www.drutex.eu/media/_upload/produkty/mb-70/video-okno/okno_mb_70.mp4",
    options: {
      firstOption:
        "The modern aluminum system used for production an exterior architectural elements that require thermal and acoustic insulation.",
      secondOption: [
        "Windows in MB-70 and MB-70HI systems may be used both in individual assembly and in aluminum facades",
        "Wide selection of colours in standard range will satisfy the most demanding clients",
        "Profiles shape allows to obtain slim and long-lasting window and door structures.",
        "Tightness is ensured by the application of special seals made of two-component synthetic rubber EPDM, solid and cellular,  that guarantees long lasting during usage and very good thermal insulation",
        "Wide range of thickness guarantees the possibility to apply all standard and non-standard glass.",
      ],
      thirdOption: ["MB-45", "MB-70HI", "IGLO 5", "MB-86SI"],
    },
    material: [
      "Windows in MB-70 and MB-70HI systems may be used both in individual assembly and in aluminum facades.",
      "Glass packages up to 50mm.One-chamber glass package with thermal transmittance of Ug=1,0 W/(m2K) according to PN-EN674 in stadard. Three-glass package of Ug=0,5 W/(m2K) coefficient or four-glass with krypton of Ug=0,3 W/(m2K) also possible to use. Glass with enhanced sound insulation, tempered, safety, anti-burglary, ornament and solar protective easy to get.",
      "Maco Multi Matic KS with two anti-burglary bolts in standard. Window equipped with a blockage against handle misplacement and a sash lift *; micro-ventilation in a slot **; *Depending on the window height **for tilt and turn windows",
    ],
  },
  {
    name: PRODUCTS.allProducts.aluminiumProzor3,
    imgCover: IMAGE.aluminiumProzor3CoverImg,
    imgVideo: "https://www.drutex.eu/media/_upload/produkty/mb-70hi/video-okno/okno_mb_70.mp4",
    options: {
      firstOption:
        "The modern aluminum system used for production of exterior architectural elements that require thermal and acoustic insulation.",
      secondOption: [
        "Window in MB-70HI system may be used both in individual assembly and in aluminium facades",
        "High thermal insulation with special insulating inserts application.",
        "Very good heat transfer coefficient U thanks to the application of thermal separators and gaskets",
        "Wide selection of colours in  standard range will satisfy the most demanding clients. ",
        "Profile shape allows to obtain slender and durable window and door structures. ",
        "Tightness is ensured by the application of special seals made of two-component synthetic rubber EPDM, solid and cellular,  that guarantees long lasting usage and very good thermal insulation.",
      ],
      thirdOption: ["MB-45", "MB-70", "MB-86SI"],
    },
    material: [
      "Windows in MB-70 and MB-70HI systems may be used both in individual assembly and in aluminum facades",
      "Glass packages up to 50mm. One-chamber glass package with thermal transmittance of Ug=1,0 W/(m2K) according to PN-EN674 in standard. The possibility to apply a three-glass package of U=0,5 W/(m2K) coefficient or four-glass with krypton of U=0,3 W/(m2K). Glass with enhanced sound insulation, tempered, safety, anti-burglary, ornament, solar protctive avaiable.",
      "Maco Multi Matic KS in standard two anti-burglary bolts. Window also has a blockage against handle misplacement and a sash lift *; micro-ventilation in a slot **; *Depending on the window height **for tilt and turn windows",
    ],
  },
  {
    name: PRODUCTS.allProducts.aluminiumProzor4,
    imgCover: IMAGE.aluminiumProzor4CoverImg,
    imgVideo: "https://www.drutex.eu/media/_upload/produkty/mb-86si/okna/anim/mb_86_si_okno.mp4",
    options: {
      firstOption:
        "The modern aluminum system used for production of exterior architectural elements that requires thermal and acoustic insulation.",
      secondOption: [
        "Windows in MB-86 SI system may be used both in   individual buildings and in aluminum facades. ",
        "Increased thermal insulation of MB-86SI system thanks to the application of an extra chamber in the thermal break.  ",
        "Very good heat transmittance coefficient U thanks to the application of thermal breaks.",
        "Great choice of colours in the standard colour range enables to satisfy the  of most demanding clients.",
        "The profile shape enables to obtain slender and resistant structure of the windows and doors.",
        "Tightness is ensured thanks to the application of special gaskets made of two-component EPDM synthetic rubber: solid and cellular, that provides many years of exploitation as well as great thermal insulation.",
        "Wide range of filling thickness guarantees the possibility to use any standard and non-standard glass. ",
      ],
      thirdOption: ["MB-45", "MB-70HI", "MB-70"],
    },
    material: [
      "This profile has a three-chamber structure with the structural depth of the window sections  77  mm (frames) and 86 mm (sash), with a thermal break made of polyamide reinforced with fiberglass. Extra chamber in the thermal break.",
      "Glass packages up to 65mm;in standard one-chamber glass package of heat transfer coefficient Ug = 1,0 W/(m2K) according to PN-EN674; he possibility to apply a three-glass package of U= 0,5 W/(m2K) coefficient or a four-glass package filled with krypton of Ug=0,3 W/(m2K);   the possibility to apply glass with increased acoustic insulation, tempered, safety, anti-burglary, ornament, solar protective.",
      "Maco Multi Matic KS fittings with two anti-burglary bolts in standard; the window is equipped with a  blockage against handle misplacement and with a sash lift*; micro-ventilation in a slot  **;",
    ],
  },
  {
    name: PRODUCTS.allProducts.ulaznaVrata,
    imgCover: IMAGE.ulaznaVrataCoverImg,
    imgVideo: "https://www.drutex.eu/media/_upload/produkty/drzwi-iglo5/video/drzwi_iglo_5.mp4",
    options: {
      firstOption: "A perfect combination of modern looks and rounded profile lines.",
      secondOption: [
        "Good thermal and acoustic insulation parameters.",
        "A wide range of Renolit foils and the possibility to apply a number of door fillings, that enables a vast array of interior designs.",
        "High safety level guaranteed by high-quality door fittings. ",
        "Elegant design that matches current architectural trends. ",
        "Possibility to choose from a wide selection of shapes and patterns which create a unique character.",
        "Application of low threshold that ensures comfortable usage.",
        "The possibility to execute in the so-called thin wielding technology (V-Perfect), that allows to connect the profiles perfectly and it guarantees better clamp and wielding control, and, as a result, very good parameters in the resistance tests of the corners.",
      ],
      thirdOption: ["IGLO Energy"],
    },
    material: [
      "Frame and sash profiles are made exclusively of prime material in A class, with profile depth 70 mm.",
      "In standard, one-chamber glass package with thermal transmittance Ug = 1,0 W/(m2K)  according to the PN-EN674 norn,  the possibility to apply three-glass package with Ug = 0,6 W/(m2K)  coefficient; the possibility to apply glasses with enhanced sound insulation, tempered, safety, anti-burglary, ornament or solar protective. Wide range of door fillings.",
      "3-point automatic bolt espagnolette; 3 hinges.",
    ],
  },
  {
    name: PRODUCTS.allProducts.pregradnaVrata,
    imgCover: IMAGE.pregradnaVrataCoverImg,
    imgVideo: "https://www.drutex.eu/media/_upload/produkty/drzwi-iglo-energy/video/drzwi_iglo_energy.mp4",
    options: {
      firstOption: "Modern design and perfect thermal insulation properties.",
      secondOption: [
        "Great thermal insulation parameters as a result of the optimal profile structure and innovative EPDM sealing system.",
        "A wide range of Renolit foils and the possibility to apply a number of door fillings enables a vast array of interior designs.",
        "Long usage and structure stability.",
        "High safety level guaranteed by high-quality door fittings. ",
        "Elegant design that matches current architectural trends.",
        "Possibility to choose from a wide range of shapes and patterns that create a unique character.",
        "Application of low threshold ensures comforable usage.",
        "The possibility to execute in the so-called thin wielding technology (V-Perfect), that allows to connect the profiles perfectly and it guarantees better clamp and wielding control, and, as a result, very good parameters in the resistance tests of the corners.",
      ],
      thirdOption: ["IGLO 5"],
    },
    material: [
      "7-chamber frame profile  and 5-chamber sash profile are made exclusively of prime material in A-class with installation depth 82 mm.",
      "Glazing - maximal glazing thickness 48 mm; glass package  4/18/4/18/4 with thermal transmittance of Ug = 0,5 W/(m2K) in standard; the possibility to apply four-glass package filled with krypton with Ug = 0,3 W/(m2K); the possibility to apply glasses with enhanced sound insulation, tempered, safety, anti-burglary, ornament and solar protecticve; a wide range of door fillings.",
      "3-point automatic espagnolette MACO; hinges made of aluminum which stands out with great durability.",
    ],
  },
  {
    name: PRODUCTS.allProducts.vrataHladanProfil,
    imgCover: IMAGE.vrataHladanProfilCoverImg,
    imgVideo: "https://www.drutex.eu/media/_upload/produkty/mb-45/video-drzwi/drzwi-mb-45.mp4",
    options: {
      firstOption: "Slim and modern door structure.",
      secondOption: [
        "The modern and stable aluminum profile allows to achieve the effect of same frame and sash level on the outside after the doors has been closed.",
        "Possibility to customize the interior as a result of the wide  range of RAL colours.  ",
        "The system is compatible with the other aluminum systems from DRUTEX offer.",
        "The system allows to apply one- or two- glass packages ",
        "Tightness is ensured by the application of special seals made of synthetic EPDM rubber.",
        "High comfort of usage and minimal need for maintenance, and long time of durability.",
        "In the offer the doors are available with low threshold or without it.",
      ],
      thirdOption: ["MB-70HI", "IMB-86SI", "MB-70", "MB-78EI Fire-Doors"],
    },
    material: [
      "Aluminum profile with installation depth 45mm (frame) and 45mm (sash).",
      "Available glass packages up to 24mm; the possibility to apply glasses with enhanced sound insulation, tempered, safety, anti-burglary, ornament, or solar protective. Wide range of door fillings.",
      "3-point automatic espagnolette MACO; hinges made of aluminum which stands out with great durability. Optionally lock with one point latch bolt.",
    ],
  },
  {
    name: PRODUCTS.allProducts.vrataProfilTermo,
    imgCover: IMAGE.vrataProfilTermoCoverImg,
    imgVideo: "https://www.drutex.eu/media/_upload/produkty/mb-70/video-drzwi/drzwi_mb_70_.mp4",
    options: {
      firstOption: "The modern and resistant aluminum doors that represent elegant design and high safety level.",
      secondOption: [
        "Doors in MB-70 system constitute the perfect solution that combines durability, aesthetics and modern design.",
        "Huge choice in the RAL color range allows to match any architectural style.",
        "High-quality aluminum profiles resist adverse effects of weather conditions.",
        "Door made in this system stand out for elegance and modern design, and at the same time they guarantee high parameters in energy efficiency  thanks to the innovative EPDM seal system.",
      ],
      thirdOption: ["MB-70HI", "MB-86SI", "MB-45", "MB-78EI Fire-Doors"],
    },
    material: [
      "System profiles have a three-chamber structure with the constructional depth 70 mm with a thermal break made of polyamide, that is reinforced with glass fiber and special inserts that insulate the section inside and the space between window panes in MB-70.",
      "Glass packages are available with thickness up to 50mm; one-chamber glass package with thermal transmittance Ug = 1,0 W/(m2K) according to the PN-EN674 norm in standard; the possibility to apply a three-glass package with Ug = 0,5 W/(m2K) or four-glass with krypton with Ug = 0,3 W/(m2K); the possibility to apply glasses with enhanced sound insulation, tempered,  safety, anti-burglary, ornament or solar protective. Wide range of door fillings is available.",
      "3-point automatic espagnolette MACO; hinges made of aluminum which stands out with great durability. Optionally lock with one point latch bolt.",
    ],
  },
  {
    name: PRODUCTS.allProducts.vrataSkrivenoKrilo,
    imgCover: IMAGE.vrataSkrivenoKriloCoverImg,
    imgVideo: "https://www.drutex.eu/media/_upload/produkty/mb-70hi/video-drzwi/drzwi_mb_70_hi.webm",
    options: {
      firstOption: "The modern and resistant aluminum doors stand out for high durability and energy efficiency.",
      secondOption: [
        "Doors in MB-70HI system feature higher level of thermal insulation resulting from the application of special insulation inserts and thermal breaks as well as gaskets made of EPDM two-component synthetic rubber: solid and cellular.",
        "Doors made in this system are a great solution also for energy-efficient building.",
        "Possibility to choose from the wide RAL color range.",
        "High-class fittings applied in the aluminum doors give great protection against burglary. ",
      ],
      thirdOption: ["MB-86SI", "MB-70", "MB-45", "MB-78EI Fire-Doors"],
    },
    material: [
      "System profiles have a three-chamber structure with the constructional depth 70 mm with a thermal barrier made of polyamide that is reinforced with glass fiber and with special inserts that insulate inside the section and the space between window panes in MB-70HI.",
      "Glass packages are available with thickness up to 50mm; one-chamber glass package with thermal transmittance Ug = 1,0 W/(m2K) according to the PN-EN674 norm in standard; the possibility to apply a three-glass package with Ug = 0,5 W/(m2K) or four-glass with krypton with Ug = 0,3 W/(m2K); the possibility to apply glasses with enhanced sound insulation, tempered,  safety, anti-burglary, ornament or solar protective. Wide range of door fillings is available.",
      "3-point automatic espagnolette MACO; hinges made of aluminum which stands out with great durability. Optionally lock with one point latch bolt.",
    ],
  },
  {
    name: PRODUCTS.allProducts.celicnaVrata,
    imgCover: IMAGE.vrataSkrivenoKriloCoverImg,
    imgVideo: "https://www.drutex.eu/media/_upload/produkty/drzwi-softline/video/drzwi_softline_68.mp4",
    options: {
      firstOption: "Perfect combination of high quality and natural beauty",
      secondOption: [
        "Elegant design reflected in the beautiful form of the rounded profile with streamline shape. Doors are available in two types of wood: pine, meranti 450.",
        "High quality achieved through application of top components and the use of selected wood for production.",
        "Focus on ecology thanks to the application of natural wood and special water-based types of varnish.",
        "Perfect woodwork durability thanks to the aluminum board that protects the wood against UV rays and water flowing from the glass and  thermos-drip that facilitates water drainage.",
        "Wide possibilities to customize the interior resulting from great selection of covering and transparent paints.",
        "Curved doors avaiable.",
        "High level of energy efficiency provided by the optimum quality of materials used for production, special sealing system and the proper glass package.",
        "Application of low threshold that ensures easy usage.",
      ],
      thirdOption: ["IGLO Energy", "IGLO Energy Classic", "IGLO 5", "IGLO 5 Classic"],
    },
    material: [
      "68mm profile in two types of wood: three -layer solid square timber: meranti 450+,  pine.",
      "Max. glass package is 32 mm with thermal transmittance of  Ug=0,8. The possibility to apply glass with enhanced sound insulation, tempered, safety, anti-burglary, ornament, solar protection .Wide range of door fillings.",
      "3-point bolt espagnolette and 3 hinges.",
    ],
  },
  {
    name: PRODUCTS.allProducts.pvcRoletne1,
    imgCover: IMAGE.pvcRoletne1Img,
    imgVideo: "https://www.drutex.eu/media/_upload/produkty/rolety-adaptacyjne/video/roleta-pologragla_WmBlhir.mp4",
    options: {
      firstOption: "Perfect solutions for the whole year – Energy efficiency, safety, privacy.",
      secondOption: [
        "Roller shutters installed on the window or in the wall, both during the house construction and in already existing buildings.",
        "They provide a perfect protection against noise and significantly improve the quality of life in the flat.",
        "They decrease heat energy needs in the building, reducing heating and air-conditioning costs in the building.",
        "Through application of a mosquito net they give a perfect protection against insects, mosquitos etc.",
        "They increase safety level as an extra anti-burglary protection.",
        "Manual and automatic control possibilty.",
        "Wide colour range allows to match to the colours of the building, windows etc.",
      ],
      thirdOption: ["MB-70HI", "MB-70", "MB-45", "MB-78EI Fire-Doors"],
    },
    material: [
      "The system profiles have a three-chamber structure with the structural depth of the door 77  mm with a thermal break made of polyamide, that is reinforced with fiberglass. ",
      "Glass packages up to 55mm; in standard the one-chamber glass package with heat transfer coefficient Ug = 1,0 W/(m2K) according to the PN-EN674 norm; the possibility to apply a three-glass package with Ug= 0,5 W/(m2K) coefficient or a four-glass package filled with krypton and Ug=0,3 W/(m2K);   the possibility to apply glasses with increased acoustic insulation, tempered, safety, anti-burglary, ornament or solar protective.",
      "3-point automatic espagnolette MACO; hinges made of aluminum which stands out with great durability. Optionally lock with one point latch bolt.",
    ],
  },
  {
    name: PRODUCTS.allProducts.pvcRoletne2,
    imgCover: IMAGE.pvcRoletne2Img,
    imgVideo: "https://www.drutex.eu/media/_upload/produkty/rolety-nakladane/video/roleta-pvc.mp4",
    options: {
      firstOption: "Perfect solutions for the whole year – Energy efficiency, safety, privacy.",
      secondOption: [
        "External PVC roller shutters is a system of shutters integrated with the window. It may be applied for buildings under construction or when exchanging windows.",
        "The wide color range of boxes and guide rails made of PVC and of aluminum armors.",
        "Possibility of  a complete build-in of the box internally and externally, so that the only visible parts are the  guide, the aluminum armor and the lower revision cover, which improves the shutters aesthetics after installation.",
        "Access to the box for maintenance purposes is possible after the opening of the bottom or the internal revision.",
        "The possibility to produce a roller shutter with a built-in mosquito net.",
        "High thermal and acoustic insulation guarantee usage comfort.",
        "The innovative elements of the roller shutter structure connected with the presence of the adapter and the reinforcing console distinguish the system from structures of other producers, guaranteeing exceptional tightness and durability. ",
      ],
      thirdOption: ["Roller shutters with Styrofoam box"],
    },
    material: [
      "The system profiles have a three-chamber structure with the structural depth of the door 77  mm with a thermal break made of polyamide, that is reinforced with fiberglass. ",
      "Glass packages up to 55mm; in standard the one-chamber glass package with heat transfer coefficient Ug = 1,0 W/(m2K) according to the PN-EN674 norm; the possibility to apply a three-glass package with Ug= 0,5 W/(m2K) coefficient or a four-glass package filled with krypton and Ug=0,3 W/(m2K);   the possibility to apply glasses with increased acoustic insulation, tempered, safety, anti-burglary, ornament or solar protective.",
      "3-point automatic espagnolette MACO; hinges made of aluminum which stands out with great durability. Optionally lock with one point latch bolt.",
    ],
  },
  {
    name: PRODUCTS.allProducts.spoljneRoletne,
    imgCover: IMAGE.spoljneRoletneImg,
    imgVideo: "https://www.drutex.eu/media/_upload/produkty/rolety_eps/wideo/animacja_produktow_na_www.mp4",
    options: {
      firstOption:
        "Thermal and sound insulation, as well as the possibility to obtain a higher class of burglary protection.",
      secondOption: [
        "The roller shutter box is made of high-density  EPS Styrofoam (expanded polystyrene).idual building and aluminum facades.",
        "The box has tests/certificates in: sound absorption, fire resistance and thermal insulation. ",
        "The application of the roller shutters significantly improves sound insulation by creating an extra barrier against external noise. The box itself as a standard ensures sound-proofing at 45 dB",
        "The construction and structure of the roller shutter facilitates plastering and façade treatment.",
        "Possibility to install the boxes directly on the concrete lintels thanks to the application of a steel console.",
        "The installation of the mosquito net is possible on the outside and on the inside of the roller shutter armor, which improves the structure aesthetics.",
      ],
      thirdOption: ["PVC SHUTTERS"],
    },
    material: [
      "The system profiles have a three-chamber structure with the structural depth of the door 77  mm with a thermal break made of polyamide, that is reinforced with fiberglass. ",
      "Glass packages up to 55mm; in standard the one-chamber glass package with heat transfer coefficient Ug = 1,0 W/(m2K) according to the PN-EN674 norm; the possibility to apply a three-glass package with Ug= 0,5 W/(m2K) coefficient or a four-glass package filled with krypton and Ug=0,3 W/(m2K);   the possibility to apply glasses with increased acoustic insulation, tempered, safety, anti-burglary, ornament or solar protective.",
      "3-point automatic espagnolette MACO; hinges made of aluminum which stands out with great durability. Optionally lock with one point latch bolt.",
    ],
  },
  {
    name: PRODUCTS.allProducts.unutrasnjeRoletne,
    imgCover: IMAGE.unutrasnjeRoletneImg,
    imgVideo: "https://www.drutex.eu/media/_upload/produkty/s-50/video/mb-sr50n_hi_f.mp4",
    options: {
      firstOption: "Modern glass-aluminium systems distinguished by their high resistance and long-term durability.",
      secondOption: [
        "The possibility to achieve modern architecture of the building thanks to the shape of columns and pins that allows to build aesthetic facades with narrow dividing lines.",
        "High parameters of tightness and thermal insulation.",
        "Structure durability and resistance thanks to the high-quality aluminium profiles.",
        "Wide application options that allows to fulfill technically advanced expectations of investors, designers and architects. ",
        "The possibility to make curtain walls in various shapes thanks to high static parameters of the profiles.",
        "Variations of interior designs, thanks to a number of different glazing types, e.g. anti-reflective , safety glass.",
        "Wide range of RAL colours gives You freedom in shaping the facades.",
      ],
      thirdOption: ["PVC SHUTTERS"],
    },
    material: [
      "The width of columns and bolts up to 50 mm, and the installation depth adopted to construction loads of the building; profile structure compatible with other window and door systems; application of a continuous thermal separator, and for MB-SR50 N HI profiles additionally a special insulating insert inside the section and the under window space.",
      "The possibility to apply glass with enhanced sound insulation, tempered, safety, anti-burglary, ornament and solar protective.",
      "3-point automatic espagnolette MACO; hinges made of aluminum which stands out with great durability. Optionally lock with one point latch bolt.",
    ],
  },
  {
    name: PRODUCTS.allProducts.podvasadneRoletne,
    imgCover: IMAGE.podvasadneRoletneImg,
    imgVideo: "https://www.drutex.eu/media/_upload/produkty/mb-wg60/video/mb-wg60-002.mp4",
    options: {
      firstOption:
        "The modern aluminum system enables to create winter gardens, hothouses and verandas that stand out for maximum access to daylight and high energy efficiency.",
      secondOption: [
        "The possibility to build very sophisticated and various arrangements, roof structures and  terrace spaces.",
        "Modern and aesthetic structure with an integrated system for draining rain water.",
        "Freedom in choice  of colors and glazing types.",
        "Durable and resistant structure for years thanks to the application of high-quality aluminum profiles.",
        "Usage comfort ensured by access to a lot of daylight.",
        "Individually devised garden structure, made of aluminum resistant to adverse weather conditions that ensures high stability and long-lasting durability",
        "The possibility to equip windows in the winter garden with a smart control system with a remote control, a tablet or a smartphone.",
        "The possibility to apply various glass combinations: safe glass, anti-burglary, ornament, hardened etc.",
        "The possibility to apply various glass combinations: safe glass, anti-burglary, ornament, hardened etc.",
        "The system is equipped with the optimum drainage and ventilation systems.",
        "The system profiles adopt next-generation special chamber separators so that they increase thermal insulation and resistance of winter gardens.  ",
      ],
      thirdOption: ["PVC SHUTTERS"],
    },
    material: [
      "Aluminium profile with a thermal separator, compatible with other window systems made of i.a. PCV, aluminum and wood.",
      "The possibility to apply glass with enhanced sound insulation, tempered, safety, anti-burglary, ornament, solar protective",
      "3-point automatic espagnolette MACO; hinges made of aluminum which stands out with great durability. Optionally lock with one point latch bolt.",
    ],
  },
  {
    name: PRODUCTS.allProducts.FunderFasade,
    imgCover: IMAGE.FunderFasade,
    imgVideo: "https://www.drutex.eu/media/_upload/produkty/iglo-hs/video/sd/iglo_hs.mp4",
    options: {
      firstOption:
        "Perfect solution for the trendy large-size terrace and balcony glazing that makes the interior absolutely unique.",
      secondOption: [
        "Modern design offering the possibility to produce large-size glazing that guarantees maximum access to the daylight. ",
        "Perfect functionality and comfortable usage thanks to the technological advancement of the profile and the fittings system.",
        "Lightness and tightness of the structure, thanks to the specially designed system of guide rails and velour EPDM sealing.",
        "Safety is guaranteed by the the stable construction, even with the sash with weight 400 kg.",
        "Possibility to customize the interior as a result of the wide range of colours.",
        "Great functionality ensured by i.a. the low aluminum threshold that can be hidden in the floor. ",
        "Perfect solution for energy-efficient and passive houses due to the big glazing surface.",
        "The unique style of the system is emphasized by the aluminum handles and knob-handles.",
        "Great functionality and intelligent solutions as a result of optional installation of automatic drive controlled by a button and a remote control.",
        "The possibility to execute in the so-called thin wielding technology (V-Perfect), that allows to connect the profiles perfectly and it guarantees better clamp and wielding control, and, as a result, very good parameters in the resistance tests of the corners.",
      ],
      thirdOption: ["MB-77 HS/MB-77 HS HI", "DUOLINE HS", "SOFTLINE HS"],
    },
    material: [
      "7-chamber original profile of the frame is made exclusively of prime material in A-class with sash depth 82mm and frame depth 194mm; maximal sash weight up to 400 kg.",
      "Glass package 4/18/4/18/4 with the heat transmittance coefficient Ug = 0,5 (W/m²K) in standard. The option to apply a four-glass package filled with krypton with Ug = 0,3 W/(m2K). Maximum glazing thickness up to 48 mm. The possibility to apply glasses with enhanced sound insulation, tempered, safety, anti-burglary, ornament or solar protective.",
      "Lift and side GU fittings in standard, three locking bolts and micro ventilation bolt. Possibility to produce the sash with weight 400 kg.",
    ],
  },
  {
    name: PRODUCTS.allProducts.VentilFasade,
    imgCover: IMAGE.VentilFasade,
    imgVideo: "https://www.drutex.eu/media/_upload/produkty/drzwi-mb77-hs/video/mb77hs.mp4",
    options: {
      firstOption:
        "Big and robust aluminum lift and slide doors in modern design that are perfect for single-family houses, as well as for luxurious apartments and hotels.",
      secondOption: [
        "The possibility to execute large structures as a result of the application of high-quality aluminum profiles.",
        "Possibility to produce big glazing that ensures access to daylight in the room. ",
        "A lot of daylight in the room ensured by the possibility to execute large-size structures.",
        "High energy efficiency level ensured by the application of a thermal break.",
        "Trendy structures are the comfortable wayout to the balcony, terrace or garden space.",
        "Thanks to the modern design and comfortable usage,  the door does not take up the space in the room after opening .",
        "The wide color range from RAL palette is an asset of aluminum doors.",
        "Great functionality and intelligent solutions thanks to  installation of automatic drive whick can be controlled by a button or a remote control.",
      ],
      thirdOption: ["IGLO-HS", "DUOLINE HS", "SOFTLINE HS"],
    },
    material: [
      "Aluminum profile with a thermal break and installation frame depth 174mm and sash depth – 77mm, optionally available in HI version with special insulating inserts inside the section and the space under window panes.",
      "Glass packages available up to 55 mm. One-chamber glass package with thermal transmittance - Ug =1,0 W/(m2K) according to the PN-EN674 norm in standard. The possibility to apply three-glass package with Ug = 0,5 W/(m2K) coefficient the possibility to apply glasses with enhanced sound insulation, tempered, safety, anti-burglary, ornament or solar protective. Steel galvanized spacer frame in standard, optionally Swisspacer Ultimate available in various colour options.",
      "Lift and slide, two locking points and micro ventilation bolt in standard; possibility to produce a sash with weight of 400 kg.",
    ],
  },
  {
    name: PRODUCTS.allProducts.strukovna,
    imgCover: IMAGE.strukovna,
    imgVideo: "https://www.drutex.eu/media/_upload/produkty/duoline-hs/video/duoline_hs.mp4",
    options: {
      firstOption: "Elegant, durable lift and slide doors in wood and aluminum technology.",
      secondOption: [
        "High-quality wooden profiles available in three depth options and in three wood types, ensuring classic look that matches perfectly the flat interior.",
        "A number of colour combinations both for wooden profiles and the aluminium clads. ",
        "A possibility to produce large-size glazing that guarantees access to daylight in the room.",
        "Aluminium profile stability and safety combined with MACO fittings. ",
        "Easy to maintenance and care.",
        "Focus on ecology thanks to the application of natural wood and special water-based types of varnish",
        "Freedom in interior design cose great selection of covering (RAL) and transparent paints.",
        "High level of energy efficiency and sound insulation ensured by the optimum quality of materials used for production, special sealing system and the proper glass packages.",
      ],
      thirdOption: ["IGLO-HS", "MB-77 HS/MB-77 HS HI", "SOFTLINE HS"],
    },
    material: [
      "Possibility to choose between profiles with three installation depths: 68mm, 78mm, 88 mm in two types of wood: three- or four-layer solid square timber: meranti 450+, pine, with aluminum clad on the outside.",
      "Two-glass package of 24 mm thickness with thermal transmittance coefficient of  Ug = 1,0 W/(m2K)) according to PN-EN674 in standard. The possibility to apply three-glass packages. For Duoline 68 mm – max. glass package is  46 mm with thermal transmittance coefficient of Ug = 0,6 W/(m2K). For Duoline 78 mm - max. glass package is 50 mm with thermal transmittance coefficient of Ug = 0,5 W/(m2K). For Duoline 88 mm – max. glass package is 50 mm with thermal transmittance coefficient of Ug = 0,5 W/(m2K) with three-glass package. Glass with enhanced sound insulation, temepred, safety, anti-burglary, ornament, and solar protecitve avaiable to use. ",
      "Lift and slide MACO in standard with two locking bolts and micro ventilation bolt.",
    ],
  },
  {
    name: PRODUCTS.allProducts.standardna,
    imgCover: IMAGE.standardna,
    imgVideo: "https://www.drutex.eu/media/_upload/produkty/softline-hs/video/sl68hs.mp4",
    options: {
      firstOption: "Elegant, wooden lift and slide doors in classic styles!",
      secondOption: [
        "High-quality wooden profiles available in three depth options.",
        "The possibility to execute large glazing that ensure access to daylight in the room. ",
        "Elegant design reflected in the beautiful form of the rounded profile with slim shape of smooth, shiny surface. ",
        "Doors are available in two types of wood: pine, meranti 450.",
        "High quality achieved through application of top components and the use of selected wood for production.",
        "Focus on ecology thanks to the application of natural wood and special water-based types of varnish.",
        "Wide possibilities to customize the interior resulting from great selection of covering and transparent paints.",
        "High level of energy efficiency ensured by the optimum quality of materials used for production, special sealing system and the proper glass packages.",
      ],
      thirdOption: ["IGLO-HS", "MB-77 HS/MB-77 HS HI", "DUOLINE HS"],
    },
    material: [
      "Choice between profiles 68 mm, 78 mm and 88 mm in two types of wood: three- or four-layer solid square timber: meranti 450+,  pine.",
      "Rwo-glass package of 24 mm thickness, with thermal transmittance coefficient of  Ug =1,0 W/(m2K) according to PN-EN674 in standard. The possibility to apply three-glass packages. For Duoline 68 mm – max. glass package is  42 mm with thermal transmittance coefficient of Ug = 0,6 W/(m2K). For Duoline 78 mm - max. glass package is 48 mm with thermal transmittance coefficient of Ug = 0,5 W/(m2K). For Duoline 88 mm – max. glass package is 50 mm with thermal transmittance coefficient of Ug = 0,5 W/(m2K) with three-glass package. The possibility to apply glass with enhanced sound insulation, tempered, saftye, anti-burglary, ornament, solar protective.",
      "Lift and slide MACO with two locking bolts and micro ventilation bolt.",
    ],
  },
  {
    name: PRODUCTS.allProducts.granit,
    imgCover: IMAGE.granit,
    imgVideo: "https://www.drutex.eu/media/_upload/produkty/iglo_light_psk/video/iglo_light_uchylno_przesuwne-1.mp4",
    options: {
      firstOption:
        "A unique design providing great light exposure inside the house and maintaining excellent energy efficiency parameters.",
      secondOption: [
        "It is an original system distinguished by its modern design and large glass surface whoch quaranties access to daylight.",
        "The system features rounded shapes and a harmonious appearance.",
        "Excellent functionality and comfortable use thanks to its technologically advanced profile and fittings system.",
        "Freedom in interior design thanks to a wide range of colours and accessories.",
        "V-Perfect in standard, that allows to connect the profiles perfectly and it guarantees better clamp and wielding control, and, as a result, very good parameters in the resistance tests of the corners.",
      ],
      thirdOption: ["IGLO ENERGY PSK", "IGLO5 PSK", "MB-70/ MB-70HI PSK", "DUOLINE PSK", "Softline PSK"],
    },
    material: [
      "A five-chamber profile of frame and sash, made exclusively of A-class prime material  for an installation depth of 70 mm.",
      "Single-chamber glass package with heat transfer coefficient Ug = 1.0 W/(m2K), according to PN-EN674 in standard.; It is possible to use a three-glass package with a coefficient of Ug = 0.7 W/(m2K).The maximum glass thickness is 36 mm. Possibilty to use glazing with higher acoustic insulation properties, tempered glass, safety glass, anti-burglary glass, ornaments or solar protective one.",
      "Four anti-burglary bolts in standard.",
    ],
  },
  {
    name: PRODUCTS.allProducts.pvcVekaSlide,
    imgCover: IMAGE.pvcVekaSlide,
    imgVideo: "https://www.drutex.eu/media/_upload/produkty/iglo_pks/video/iglo_uchylno_przesowne.mp4",
    options: {
      firstOption:
        "Perfect solution, that ensures big access to daylight both in small and big rooms, maintaining great thermal insulation at the same time.",
      secondOption: [
        "Great solution for small rooms. It does not take up usable space while opening.",
        "Big glazing surface ensures more daylight in the room.",
        "Energy efficiency, thanks to the optimal structure of the profile, specially designed EPDM sealing system and glass packages with low thermal transmittance coefficients. ",
        "Modern design, ensured by the slim and round-shaped profiles.",
        "High safety level guaranteed by  four anti-burglary bolts in standard. ",
        "Wide range of colour range, that enables numerous interior design styles.",
        "Very good parameters of sound insulation ensure acoustic comfort even in places with intense traffic.",
        "Great parameters of air permeability and water resistance as a result of triple sealing.",
        "Thanks to optimal reinforcement the system offers great reistance to the wind load.",
        "The possibility to execute in the so-called thin wielding technology (V-Perfect), that allows to connect the profiles perfectly and it guarantees better clamp and wielding control, and, as a result, very good parameters in the resistance tests of the corners (Iglo Energy Classic).",
      ],
      thirdOption: ["IGLO LIGHT PSK", "IGLO5 PSK", "MB-70/ MB-70HI PSK", "DUOLINE PSK", "Softline PSK"],
    },
    material: [
      "7-chamber frame and sash profiles are made exclusively of a prime material in A-class with installation depth of 82 mm.",
      "Glass package of 4/18/4/18/4 with thermal transmittance  Ug = 0,5 W/(m2K) in standard. The possibility to apply four-glass package filled with krypton and Ug = 0,3 W/(m2K); maximal glazing thickness up to 48 mm. The possibility to apply the glasses with enhanced sound insulation, tempered, safety, anti-burglary, ornament, or solar protective. ",
      "Maco Multi Matic KS fittings. There is a possibility to apply automatic fittings, that support tilt closing. Four anti-burlgary bolts.",
    ],
  },
  {
    name: PRODUCTS.allProducts.aluUltraGlide,
    imgCover: IMAGE.aluUltraGlide,
    imgVideo: "https://www.drutex.eu/media/_upload/produkty/drzwi-iglo5-psk/video/iglo_uchylno_przesowne.mp4",
    options: {
      firstOption:
        "Perfect solution that ensures big access to daylight both in small and big room, maintaining great thermal insulation at the same time.",
      secondOption: [
        "Design that reflects innovativeness and unconventionality.",
        "High safety level guaranteed by the application of four anti-burglary bolts in standard.",
        "Possibility to customize the interior as the result of the wide range of colours; ",
        "Very good thermal parameters ensure heat saving thanks to optimal structure and EPDM sealing.",
        "Good parameters in sound insulation that guarantee acoustic comfort.",
        "The possibility to execute in the so-called thin wielding technology (V-Perfect), that allows to connect the profiles perfectly and it guarantees better clamp and wielding control, and, as a result, very good parameters in the resistance tests of the corners (Iglo 5 Classic).",
      ],
      thirdOption: ["IGLO LIGHT PSK", "IGLO ENERGY PSK", "MB-70/ MB-70HI PSK", "DUOLINE PSK", "Softline PSK"],
    },
    material: [
      "5-chamber frame and sash profiles made exclusively of prime material in A-class with installation width  70 mm.",
      "One-chamber glass package with thermal transmittance Ug=1,0 W/(m²K) according to the PN-EN674 norm in standard. The possibility to apply three-glass package with Ug = 0,7 W/(m²K). Maximal glazing thickness up to 36 mm. The possibility to apply glasses with enhanced sound insulation, tempered, safety, anti-burglary, ornament or solar protective.",
      "The possibility to apply automatic fitting that supports tilt closing. Four anti-burglary bolts in standard.",
    ],
  },
  {
    name: PRODUCTS.allProducts.pvcVekaSoft,
    imgCover: IMAGE.pvcVekaSoft,
    imgVideo: "https://www.drutex.eu/media/_upload/produkty/mb-77-up/video/mb_70_uchylno-przesuwne.mp4",
    options: {
      firstOption:
        "A perfect solution for modern aluminium structures that ensures great access to daylight in small and big rooms",
      secondOption: [
        "System structures may be used both in individual assembly and in alumiinum facades.",
        "Great thermal insulation parameters thanks to the application of special insulating inserts in MB 70HI system.",
        "Resistant structure thanks to the high-quality aluminum profile.",
        "Wide possibilities to customize the interior and exterior resulting from great selection of colours.",
        "The possibility to build durable and solid  large-size structures.",
        "The usage comfort and functionality are ensured by the high-quality profiles and modern fittings that improve the smooth system operation.",
      ],
      thirdOption: ["IGLO LIGHT PSK", "IGLO ENERGY PSK", "IGLO5 PSK", "DUOLINE PSK", "Softline PSK"],
    },
    material: [
      "Profiles have a three-chamber structure with the constructional depth of the sections of 70 mm (frame), 79 mm (sash) with a thermal separator made of polyamide reinforced with glass fiber and the application of special inserts that insulate inside the section and the space between window panes in MB-70Hi system.",
      "Glass packages up to 50 mm avaiable. One-chamber glass package with thermal transmittance of Ug = 1,0 W/(m2K) according to PN-EN674. The possibility to apply a three-glass package of Ug 0,5 W/(m2K) coefficient with enhanced sound and insulating, tmepred, safety, anti-burglary, ornament, solar protective glass.",
      "Maco Multi Matic KS with  four anti-burglary bolts in standard.",
    ],
  },
  {
    name: PRODUCTS.allProducts.aluVisoglide,
    imgCover: IMAGE.aluVisoglide,
    imgVideo: "https://www.drutex.eu/media/_upload/produkty/duoline-psk/video/duoline_68_psk.mp4",
    options: {
      firstOption: "Elegant, durable tilt and slide doors in wood and aluminium technology.",
      secondOption: [
        "High-quality wooden profiles available in three depth options and in three wood types, ensuring classic look that matches perfectly the flat interior.",
        "A number of coluor combinations both for wooden profiles and the aluminium clads.",
        "A possibility to produce large-size glazing that guarantees access to daylight in the room.",
        "High safety level thanks to the aluminium profile stability combined with MACO fittings. ",
        "Easy to conservate.",
        "Focus on ecology because of special water-based types of varnish.",
        "Wide possibilities to customize the interior resulting from great selection of covering (RAL)  and transparent paints.",
        "High level of energy efficiency and sound insulation cause of optimum quality of materials used for production, special sealing system and the proper glass packages. ",
      ],
      thirdOption: ["IGLO LIGHT PSK", "IGLO ENERGY PSK", "IGLO5 PSK", "MB-70/ MB-70HI PSK", "Softline PSK"],
    },
    material: [
      "Wooden profile - 68mm in two types of wood: three- or four-layer solid square timber: meranti 450+ and pine.",
      "Two-glass package of 24 mm thickness, with thermal transmittance coefficient of  Ug=1,0 W/(m2K) according to PN-EN674 in standard. The possibility to apply two or three-glass packages. For Duoline 68 mm – max. glass package is  46 mm with thermal transmittance coefficient of Ug = 0,6 W/(m2K). Glass with enhanced sound insulation, tempered, safety, anti-burglary, ornament, solar protective.",
      "Tilt and slide MACO MULTI MATIC KS fittings with 4 locking bolts and micro ventilation bolt. ",
    ],
  },
  {
    name: PRODUCTS.allProducts.pvcSmatiaM9800,
    imgCover: IMAGE.pvcSmatiaM9800,
    imgVideo: "https://www.drutex.eu/media/_upload/produkty/softline-psk/video/sl_68_uchylno_przesuwne.mp4",
    options: {
      firstOption: "Perfect solution for the modern balcony and terrace glazing for small and big room.",
      secondOption: [
        "High-quality wooden profiles available in three depth options.",
        "The possibility to make large-size glazing that guarantee access to daylight in the room.",
        "Elegant design reflected in the beautiful form of the rounded profile with slim shape of smooth, shiny surface.",
        "Windows are available in two types of wood: pine, meranti 450.",
        "High quality achieved through top components and the use of selected wood for production.",
        "Focus on ecology thanks to the application of natural wood and special water-based types of varnish.",
        "Wide possibilities to customize the interior design from great selection of  covering and transparent paints.",
        "High level of energy efficiency ensured by the optimum quality of materials used for production, special sealing system and the proper glass packages.",
      ],
      thirdOption: ["IGLO LIGHT PSK", "IGLO ENERGY PSK", "IGLO5 PSK", "MB-70/ MB-70HI PSK", "DUOLINE PSK"],
    },
    material: [
      "Choice between profiles 68 mm, 78 mm and 88 mm in two types of wood: three- or four-layer solid square timber: meranti 450+,  pine.",
      "Two-glass package of 24 mm thickness with thermal transmittance coefficient of  Ug = 1,0 W/(m2K) according to PN-EN674 in standard. The possibility to apply three-glass packages. For Duoline 68 mm – max. glass package is 32 mm with thermal transmittance coefficient of Ug = 0,8 W/(m2K). For Duoline 78 mm - max. glass package is 44 mm with thermal transmittance coefficient of Ug = 0,6 W/(m2K). For Duoline 88 mm – max. glass package is 54 mm with thermal transmittance coefficient of Ug = 0,5 W/(m2K) with three-glass package. The possibility to apply a four-glass package with krypton with thermal transmittance coefficient of Ug=0,3 W/(m2K). Glass with enhanced sound insulation,tempered, safety, anti-burglary, ornament, solar protective avaiable.",
      "Lift and slide MACO fittings.",
    ],
  },
  {
    name: PRODUCTS.allProducts.pvcSmatiaM1980,
    imgCover: IMAGE.pvcSmatiaM1980,
    imgVideo: "https://www.drutex.eu/media/_upload/produkty/harmonijka_mb-86_fold_line/video/harmonijka-mb86.mp4",
    options: {
      firstOption:
        "The system with enhanced thermal insulation, ensuring a perfect solution for balcony and terrace enclosures and for winter gardens.",
      secondOption: [
        "Enhanced thermal insulation in the MB-86 Fold Line system thanks to the application of an extra chamber in the thermal break.",
        "Resistant and stable structure thanks to high quality aluminum profiles. ",
        "The possibility to execute aesthetic and modern large glazing that also enables to use the building space very efficiently thanks to the optimum structure of the system.",
        "Possibility of individual system arrangements that allows to apply the solution  for individual buildings as well as for aluminum facades.",
        "The folding door offers inward and outward opening and it may have any system of sash configuration.",
        "Possibility to customize the structure and to adopt it to current architectural trends thanks to the wide range of masking paints  (RAL). ",
      ],
      thirdOption: ["SOFTLINE 68"],
    },
    material: [
      "This profile has a three-chamber structure with the structural depth sections  77  mm (frames) and 86 mm (sash).",
      "The glass packages with thickness 65mm . One-chamber glass package with heat transfer coefficient Ug = 1,0 W/(m2K) according to the PN-EN674 norm in standard. The possibility to apply a three-glass package with Ug = 0,5 W/(m2K). The possibility to apply glasses with enhanced sound insulation, tempered, safety, anti-burglary, ornament or solar protective. ",
      "System fittings. ",
    ],
  },
  {
    name: PRODUCTS.allProducts.panoramaAliplast,
    imgCover: IMAGE.panoramaAliplast,
    imgVideo: "https://www.drutex.eu/media/_upload/produkty/softline-68-h/video/harmonijka_sl68.mp4",
    options: {
      firstOption: "Original and classic design with advanced technical solutions ensure maximal opening width.",
      secondOption: [
        "High-quality wooden profiles available in three depth options.",
        "The possibility to produce large-size glazing that guarantees access to daylight in the room.",
        "Elegant design that is reflected in the beautiful form of rounded profiles with smooth shape and shiny surface.",
        "Windows are available in three types of wood: pine, meranti 450+  and larch.",
        "High quality achieved with application of top components and the using of selected wood for production.",
        "Focusing on ecology thanks to the application of natural wood and special water-based types of varnish",
        "Many possibilities to customize the interior design thanks to selection of masking and transparent paints",
        "High level of energy efficiency ensured by the optimal quality of materials used for production, special sealing system and the proper glass packages.",
      ],
      thirdOption: ["MB-86 Fold Line"],
    },
    material: [
      "Profiles made in Softline 68 system are available in two types of wood: meranti 450+, pine.",
      "Two-glass package with thickness 24 mm in standard, with thermal transmittance coefficient - Ug = 1,0 W/(m2K) according to the PN-EN674 norm. The possibility to apply  three-glass packages with thermal transmittance coefficient even with Ug = 0,8 W/(m2K).  The possibility to apply glasses with enhanced sound insulation, tempered, safety, anti-burglary, ornament or solar protective. ",
      "Fittings -  MACO MULTI MATIC KS.",
    ],
  },
  // {
  //   name: "",
  //   imgCover: "",
  //   imgVideo: "",
  //   options: {
  //     firstOption: "",
  //     secondOption: [],
  //     thirdOption: [],
  //   },
  //   material: [],
  // },
];
